import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/context/admin/SidebarContext";
import { AuthProvider } from "@/components/features/auth/providers/AuthProvider";
import NotificationProvider from "@/components/providers/NotificationProvider";
import { Toaster } from "@/components/atoms/ui/toaster";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <NotificationProvider>
            <SidebarProvider>{children}</SidebarProvider>
            {/* use toaster for gender notification for action. Ex: login success or login failed */}
            <Toaster />
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
